[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
ctr = "0.9.2"
hex-literal = "0.4.1"
rand = "0.8.5"
base64 = "0.21.2"
